### ISSUE TITLE
First section - Mango Picking page (https://soopermango.com/farm-visit-pluck-n-pay)

### ISSUE THREAD

**Issue by OKhorshid** [MahmoodKhalil57/name-1#13]
![image](https://user-images.githubusercontent.com/78205308/177614827-ba1b2598-598b-48ee-9054-4445539f954d.png)
this section includes a part that is in not shown in the image, simply this section starts with the start of the page, and includes everything up until the registration form shown in the second image below, which is excluded itself & everything below it. 
![image](https://user-images.githubusercontent.com/78205308/177615708-5c855cb3-049f-426f-8c22-374cfa12edb9.png)

PS. make sure to align all paragraphs precisely like it is done on the SooperMango's Mango Picking page!

**Comment by MahmoodKhalil57** [comment]
done
