### ISSUE TITLE
Testimonials page 

### ISSUE THREAD

**Issue by OKhorshid** [MahmoodKhalil57/name-1#14]
![image](https://user-images.githubusercontent.com/78205308/178122802-998fd1ad-9ee8-40dc-ac4f-391aaa48875d.png)

check out the page and imitate the layout & photos or vids.

**Comment by OKhorshid** [comment]
first u'll need to create a vue file under pages called testimonials(check spelling), and change the route

**Comment by MahmoodKhalil57** [comment]
Done
