### ISSUE TITLE
privacy policy page

### ISSUE THREAD

**Issue by OKhorshid** [MahmoodKhalil57/name-1#22]
![image](https://user-images.githubusercontent.com/78205308/178672546-313bcc47-2d2c-4d3a-a55b-64c237a1d8f5.png)

whole page is not shown in image check page through this link: https://soopermango.com/privacy

There are alot of hyper links in there make sure that you do them all & connect them with the pages they abide to when possible.

**Comment by MahmoodKhalil57** [comment]
Done
